### PR TITLE
Fix tracking Commander in play when your commander is a (M)DFC.

### LINKED ISSUE #7530: hakka not dealing commander damage

### PR DESCRIPTION
**Pull request by Grath**
Fixes #7530, #7637, #7699, #7773

### CODE REVIEW

File: Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java [hunk 1]
```diff
@@ -36,15 +38,19 @@ public CommanderInfoWatcher(String commanderTypeName, UUID commander, boolean ch
     @Override
     public void watch(GameEvent event, Game game) {
         if (checkCommanderDamage && event.getType() == GameEvent.EventType.DAMAGED_PLAYER && event instanceof DamagedPlayerEvent) {
-            if (sourceId.equals(event.getSourceId())) {
+            Card sourceCard = game.getCard(event.getSourceId());
+            if (sourceCard instanceof DoubleFacedCardHalf) {
```
Comment (JayDi85) [inline Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java]: getcard->getmaincard instead instanceof, see https://github.com/magefree/mage/issues/14099#issuecomment-3608802574

Comment (Grath) [reply Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java]: Good call, done.

File: Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java [hunk 2]
```diff
@@ -38,10 +38,7 @@ public CommanderInfoWatcher(String commanderTypeName, UUID commander, boolean ch
     @Override
     public void watch(GameEvent event, Game game) {
         if (checkCommanderDamage && event.getType() == GameEvent.EventType.DAMAGED_PLAYER && event instanceof DamagedPlayerEvent) {
-            Card sourceCard = game.getCard(event.getSourceId());
-            if (sourceCard instanceof DoubleFacedCardHalf) {
-                sourceCard = ((DoubleFacedCardHalf) sourceCard).getParentCard();
-            }
+            Card sourceCard = game.getCard(event.getSourceId()).getMainCard();
```
Comment (xenohedron) [inline Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java]: null check?

Comment (Grath) [reply Mage/src/main/java/mage/watchers/common/CommanderInfoWatcher.java]: Done.
