### PR TITLE
Fix conditional "must be blocked if able"

### LINKED ISSUE #11432: Issue with conditional "must be blocked if able"
I've found an issue with [[Frodo Baggins]] and [[Enkira, Hostile Scavenger]].  Both must be blocked if able if a condition is met.  Creatures that must unconditionally be blocked if able function properly (I've tested [[Canopy Stalker]] and [[Gaea's Protector]] and they work as they should), but with the conditional ones, the opponent can still choose not to block even if the condition is met.  I'm quite new to Xmage development so there may be something I am missing in the code, but looking at it, I don't see why it shouldn't work.  They all use
```
MustBeBlockedByAtLeastOneSourceEffect(Duration.WhileOnBattlefield)
```
with Frodo Baggins and Enkira, Hostile Scavenger calling that within a ConditionalRequirementEffect().  The conditions seem to be correct for both cards.
```
SourceIsRingBearerCondition.instance
```
for Frodo Baggins and
```
EquippedSourceCondition.instance
```
for Enkira, Hostile Scavenger.  Does anyone know what the issue could be and if so, what would be the solution?

### PR DESCRIPTION
**Pull request by permadeath**
Fix #11432

### CODE REVIEW

File: Mage/src/main/java/mage/abilities/decorator/ConditionalRequirementEffect.java [hunk 1]
```diff
@@ -125,6 +125,16 @@ public boolean mustBlockAny(Game game) {
         return false;
     }
 
+    @Override
+    public boolean mustBlockAllAttackers(Game game) {
```
Comment (xenohedron) [inline Mage/src/main/java/mage/abilities/decorator/ConditionalRequirementEffect.java:129]: method is `mustBlockAllAttackers` but override is calling `mustBlockAny`

**Review by xenohedron — CHANGES_REQUESTED** [review]

File: Mage/src/main/java/mage/abilities/decorator/ConditionalRequirementEffect.java (hunk 1 above)
Comment (permadeath) [reply Mage/src/main/java/mage/abilities/decorator/ConditionalRequirementEffect.java:129]: Whoops, sorry about that.  Should be fixed now.

**Review by xenohedron — APPROVED** [review]
