### PR TITLE
Use spell mana value instead of card mana value for cascade

### LINKED ISSUE #14687: Cascade is incorrectly using the source card's mana value instead of the spell's mana mana value
Faced the issue testing [[Quandrix, the Proof]], but all from https://scryfall.com/search?q=o%3A%22have+cascade%22 should face the same problem.

Casting a Fireball with Cascade on X=4 should cascade the first card of mana value 4 or less.

However here it went through a Brainstorm in my library:

Image

### PR DESCRIPTION
**Pull request by matoro**
Cascade should use the mana value of the spell rather than the mana value of the card.  (Only?) relevant for X-cost spells.

No need to document rule 202.3e in `CascadeAbility` since it is already documented in `Spell.getManaValue()`.

Fixes https://github.com/magefree/mage/issues/14687

### CODE REVIEW

**Review by Grath — APPROVED** [review]

File: Mage/src/main/java/mage/abilities/keyword/CascadeAbility.java [hunk 1]
```diff
@@ -111,14 +113,14 @@ public boolean apply(Game game, Ability source) {
         if (controller == null) {
             return false;
         }
-        Card sourceCard = game.getCard(source.getSourceId());
-        if (sourceCard == null) {
+        Spell sourceSpell = game.getStack().getSpell(this.getTargetPointer().getFirst(game, source));
```
Comment (Susucre) [inline Mage/src/main/java/mage/abilities/keyword/CascadeAbility.java]: Needs to use LKI or this will fizzle if the spell leaves the stack before trigger resolution. `game.getSpellOrLKIStack` most likely.

Comment (matoro) [reply Mage/src/main/java/mage/abilities/keyword/CascadeAbility.java]: Thanks, didn't know about this function.  Added it with a test

**Review by Susucre — APPROVED** [review]

File: Mage/src/main/java/mage/abilities/keyword/CascadeAbility.java (hunk 1 above)
Comment (jeffwadsworth) [reply Mage/src/main/java/mage/abilities/keyword/CascadeAbility.java]: Any particular reason this isn't merged?
