### PR TITLE
Fix 514.3a, player priority on cleanup when something happened

### LINKED ISSUE #12090: When discarding to hand size, discard triggers can't be responded to
Tested on the most recent codebase as I write this (latest commit: 29f98589db0a564e8342970caec2e55961a9e00f).

To reproduce:
1. Have a permanent on the battlefield with an ability that triggers on discarding cards, such as Confessor.
2. Discard to hand size during your cleanup step.

Expected result: The triggered ability goes onto the stack, and you receive priority.
Actual result: The triggered ability immediately resolves without any chance to respond. (Its controller still makes required decisions such as targets.)

Tested cards known to be affected:
- Confessor (`DiscardCardPlayerTriggeredAbility`)
- Feast of Sanity (`DiscardCardControllerTriggeredAbility`)
- Tourach, Dread Cantor (`DiscardsACardOpponentTriggeredAbility`)
- Rielle the Everwise (custom triggered ability, previously reported for just this card in #6761)

### PR DESCRIPTION
**Pull request by Susucre**
The End Phase / Cleanup Step were not properly set up for 514.3a:

> 514.3. Normally, no [player](https://yawgatog.com/resources/magic-rules/#player) receives [priority](https://yawgatog.com/resources/magic-rules/#priority) [during](https://yawgatog.com/resources/magic-rules/#during) the [cleanup step](https://yawgatog.com/resources/magic-rules/#cleanup_step), so no [spells](https://yawgatog.com/resources/magic-rules/#spell) can be [cast](https://yawgatog.com/resources/magic-rules/#cast) and no [abilities](https://yawgatog.com/resources/magic-rules/#ability) can be activated. However, this rule is subject to the following exception:
514.3a. At this point, the game checks to see if any [state-based actions](https://yawgatog.com/resources/magic-rules/#state-based_actions) would be performed and/or any [triggered abilities](https://yawgatog.com/resources/magic-rules/#triggered_ability) are waiting to be put onto the [stack](https://yawgatog.com/resources/magic-rules/#stack) (including those that [trigger](https://yawgatog.com/resources/magic-rules/#trigger) "at the beginning of the next [cleanup step](https://yawgatog.com/resources/magic-rules/#cleanup_step)"). If so, those [state-based actions](https://yawgatog.com/resources/magic-rules/#state-based_actions) are performed, then those [triggered abilities](https://yawgatog.com/resources/magic-rules/#triggered_ability) are put on the [stack](https://yawgatog.com/resources/magic-rules/#stack), then the [active player](https://yawgatog.com/resources/magic-rules/#active_player) gets [priority](https://yawgatog.com/resources/magic-rules/#priority). [Players](https://yawgatog.com/resources/magic-rules/#player) may [cast](https://yawgatog.com/resources/magic-rules/#cast) [spells](https://yawgatog.com/resources/magic-rules/#spell) and [activate](https://yawgatog.com/resources/magic-rules/#activate) [abilities](https://yawgatog.com/resources/magic-rules/#ability). Once the [stack](https://yawgatog.com/resources/magic-rules/#stack) is empty and all [players](https://yawgatog.com/resources/magic-rules/#player) [pass in succession](https://yawgatog.com/resources/magic-rules/#pass_in_succession), another [cleanup step](https://yawgatog.com/resources/magic-rules/#cleanup_step) begins.

With this PR's changes, it is now working as expected:

image

As an added tweak, a `toString()` was added to all phases and steps to prevent class names to appear in the logs when extra steps happen (screenshot for additional upkeep before that change):
extra_turn_message

Fix #12090

### CODE REVIEW

File: Mage/src/main/java/mage/game/turn/BeginCombatStep.java [hunk 1]
```diff
@@ -38,4 +38,7 @@ public BeginCombatStep copy() {
         return new BeginCombatStep(this);
     }
 
+    public String toString() {
```
Comment (JayDi85) [inline Mage/src/main/java/mage/game/turn/BeginCombatStep.java:41]: Use override

Comment (Susucre) [reply Mage/src/main/java/mage/game/turn/BeginCombatStep.java:41]: oh indeed, I added the abstract ones last and forgot to go back and add the attribute.

File: Mage/src/main/java/mage/game/turn/DeclareAttackersStep.java [hunk 2]
```diff
@@ -47,4 +47,7 @@ public DeclareAttackersStep copy() {
         return new DeclareAttackersStep(this);
     }
 
+    public String toString() {
+        return "declare attackers";
```
Comment (JayDi85) [inline Mage/src/main/java/mage/game/turn/DeclareAttackersStep.java:51]: Use const with standard names like PhaseStep.DECLARE_ATTACKERS
