### PR TITLE
Fix EntersBattlefieldOneOrMoreTriggeredAbility for ZONE_CHANGE_GROUP events making tokens controlled by different players

### LINKED ISSUE #12588: Marneus Calgar missing draws
Marneus Calgar failed to draw cards under certain conditions. Opponnent made a copy of my Calgar then Gor Muldrak triggered creating 1 salamander token under my control as well as another 1 under theirs and neither of us drew a card from our respective Calgars

### PR DESCRIPTION
**Pull request by jimga150**
Fixes #12588
~~Will need the be reviewed when #11895 is implemented~~

### CODE REVIEW

**Comment by xenohedron** [comment]
So, uh, why can't you rewrite `EntersBattlefieldOneOrMoreTriggeredAbility` to use the new ZONE_CHANGE_BATCH event instead?

**Comment by jimga150** [comment]
Thought the effort was being contained to that issue. Rewritten.

File: Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java [hunk 1]
```diff
@@ -40,37 +40,31 @@ private EntersBattlefieldOneOrMoreTriggeredAbility(final EntersBattlefieldOneOrM
...
-                    return false;
-                }
-                break;
+                return enteringPermanents.anyMatch(permanent -> permanent.getControllerId().equals(this.controllerId));
             case OPPONENT:
-                if (!controller.hasOpponent(zEvent.getPlayerId(), game)) {
-                    return false;
-                }
-                break;
+                return enteringPermanents.anyMatch(permanent -> controller.hasOpponent(this.controllerId, game));
```
Comment (xenohedron) [inline Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java:65]: this line looks wrong, it should be checking `permanent.getControllerId()`. Looks like no ability currently uses TargetController.OPPONENT though.

also, should add a default case to the switch that throws an error (you can imagine a dev trying to use TargetController.ANY and it will silently never trigger)

**Review by xenohedron — APPROVED** [review]

File: Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java [hunk 2]
```diff
@@ -40,37 +40,32 @@ private EntersBattlefieldOneOrMoreTriggeredAbility(final EntersBattlefieldOneOrM
...
-        ZoneChangeGroupEvent zEvent = (ZoneChangeGroupEvent) event;
+
         Player controller = game.getPlayer(this.controllerId);
-        if (zEvent.getToZone() != Zone.BATTLEFIELD || controller == null) {
+        if (controller == null) {
             return false;
         }
 
+        ZoneChangeBatchEvent zEvent = (ZoneChangeBatchEvent) event;
+        Stream<Permanent> enteringPermanents = zEvent.getEvents().stream()
```
Comment (JayDi85) [inline Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java:55]: Do not use stream fields/params due code style. Use filter with all conditions inside.

File: Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java [hunk 3]
```diff
@@ -40,37 +40,32 @@ private EntersBattlefieldOneOrMoreTriggeredAbility(final EntersBattlefieldOneOrM
...
+                .filter(Objects::nonNull)
+                .filter(permanent -> filterPermanent.match(permanent, this.controllerId, this, game));
+
         switch (this.targetController) {
             case YOU:
-                if (!controller.getId().equals(zEvent.getPlayerId())) {
-                    return false;
-                }
-                break;
+                return enteringPermanents.anyMatch(permanent -> permanent.getControllerId().equals(this.controllerId));
```
Comment (JayDi85) [inline Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java:63]: Use getControllerId() and getTargetController() instead direct access due good code style.

Comment (xenohedron) [reply Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java]: `targetController` is fine to access directly, it's internal to this class. Still need to update to `getControllerId()` though

File: Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java [hunk 4]
```diff
@@ -40,37 +37,32 @@ private EntersBattlefieldOneOrMoreTriggeredAbility(final EntersBattlefieldOneOrM
...
-                        .map(MageItem::getId)
-                        .map(game::getPermanent)
-                        .filter(Objects::nonNull)
-        ).anyMatch(permanent -> filterPermanent.match(permanent, this.controllerId, this, game));
+        ZoneChangeBatchEvent zEvent = (ZoneChangeBatchEvent) event;
+        return zEvent.getEvents().stream()
+                .filter(z -> z.getToZone() == Zone.BATTLEFIELD)
+                .filter(z -> filterPermanent.match(z.getTarget(), this.controllerId, this, game))
+                .anyMatch(z -> {
+                    UUID enteringPermanantControllerID = z.getTarget().getControllerId();
```
Comment (xenohedron) [inline Mage/src/main/java/mage/abilities/common/EntersBattlefieldOneOrMoreTriggeredAbility.java:56]: spelling: "Permanent"
