### PR TITLE
Fix effects where the source's controller sacrifices it

### LINKED ISSUE #12582: Sacrifice from evoke doesn't resolve when control of creature changes
I had a [[Confusion in the Ranks]] out. I evoked an [[Ingot Chewer]], with the sacrifice from evoke on the bottom of the stack, resolving last of the 3 triggers. I exchanged control of the Chewer with one of my opponent's creatures, but the sacrifice never then happened once it was under their control.

### PR DESCRIPTION
**Pull request by ssk97**
Fixes #12582

Also modifies the Evoke test to use strict choose mode.

### CODE REVIEW

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java [hunk 1]
```diff
@@ -40,7 +48,7 @@ public boolean apply(Game game, Ability source) {
         if (sourceObject instanceof Permanent) {
             Permanent permanent = (Permanent) sourceObject;
             // you can only sacrifice a permanent you control
```
Comment (JayDi85) [inline Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: Looks like no needs in controller check at all — permanent must be sacrificed anyway. There are not controller check in all other usages of sacrifice.

File: Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java [hunk 2]
```diff
@@ -41,8 +41,16 @@ public void testCreatureComesIntoPlay() {
 
         castSpell(1, PhaseStep.PRECOMBAT_MAIN, playerA, "Shriekmaw");
         setChoice(playerA, true);
-        // addTarget(playerA, "Silvercoat Lion"); Autochosen, only target
+        setChoice(playerA, ""); //Stack triggers
```
Comment (JayDi85) [inline Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: Why it empty?

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java (hunk 1 above)
Comment (ssk97) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: No, there must be a check for the controller for most effects.

701.17a. To sacrifice a permanent, its controller moves it from the battlefield directly to its owner's graveyard. **A player can't sacrifice something that isn't a permanent, or something that's a permanent they don't control.** Sacrificing a permanent doesn't destroy it, so regeneration or other effects that replace destruction can't affect this action.

File: Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java (hunk 2 above)
Comment (ssk97) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: There's the creature's ETB effect and the evoke ETB effect going on the stack at the same time. The order the two triggers are stacked doesn't matter, so empty string is fine.

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java (hunk 1 above)
Comment (JayDi85) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: Can you describe real cards example with canceled sacrifice due that rule?

File: Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java (hunk 2 above)
Comment (JayDi85) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: Use real trigger name instead. Don’t use empty choice commands, it must be restricted for usage.

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java (hunk 1 above)
Comment (ssk97) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: [[Ball Lightning]]. With the trigger on the stack, cast [[Wrong Turn]] to donate it to an opponent. The Ball Lightning must survive when the trigger resolves, since you control the trigger but not the creature.

**Comment by JayDi85** [comment]
[[Ball Lightning]] [[Wrong Turn]]

File: Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java (hunk 2 above)
Comment (ssk97) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: `setChoice(playerA, "");` has been used in multiple other tests to indicate that triggers need to be stacked but order doesn't matter. Should I change all of those as well?

Comment (JayDi85) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: Yes, it can be fixed out of that PR (if there are small amount then can be fixed here).

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java (hunk 1 above)
Comment (JayDi85) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: Interesting. Another example: https://www.reddit.com/r/mtgrules/comments/186z1p1/mishrass_warform_delayed_sacrifice_trigger_if/

> The delayed trigger of "Sacrifice it at the beginning of the next end step" is a result of the resolving trigger from Mishra. (CR603.7)
> Since you controlled the original trigger, you control the delayed trigger. (CR603.7e)
> You can't sacrifice something you don't control (CR701.17a), so when the delayed trigger resolves, nothing happens.
> Contrast to [[Mizzix, Replica Rider]], which grants the sacrifice trigger to the creature itself, so whoever controls the creature when the trigger goes on the stack sacrifices it.

Result depends on source ability:
- normal ability;
- triggered ability;
- delayed triggered ability;

Looks like sacrifice usage must be research for possible bugs. It can be potentially a massive problem.

Comment (JayDi85) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: “source.isControlledBy(permanent.getControllerId()” — that’s conditional must process all use cases.

Maybe it can be moved sacrifice code:
IMG_0620

Comment (JayDi85) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: > controllerSacrifices

Maybe it can be implemented as sacrifice param.

@ssk97 can you check that cards implementation — is it affected?

https://scryfall.com/search?q=o%3A%22controller+sacrifice%22

**Comment by JayDi85** [comment]
For info: evoke and sacrifice description with rules refs
https://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/627589-reveillark-and-instant-speed-control-changing

File: Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java (hunk 1 above)
Comment (ssk97) [reply Mage/src/main/java/mage/abilities/effects/common/SacrificeSourceEffect.java:50]: Right now the `sacrifice` function implicitly assumes that the controller is sacrificing it, which is usually the correct behavior. The exceptions are here in `SacrificeSourceEffect` ("Sacrifice ~") and in `SacrificeTargetEffect` with the `playerIdThatHasToSacrifice` constructor used for cards like Gemini Engine.

I looked through that list and as far as I can tell all of the cards are already correctly implemented.

File: Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java (hunk 2 above)
Comment (ssk97) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: If the triggers being stacked have identical text is the empty string acceptable?

Comment (JayDi85) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: Yes, it’s ok. Just make sure double effects/triggers raised by design, not by error (e.g. duplicated effects).

Comment (ssk97) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: Well, it works for triggers, for replacement effects I can't actually order them because the random ID is before the effect text. I'll fix the triggers and leave replacement effect ordering for someone else.

Comment (ssk97) [reply Mage.Tests/src/test/java/org/mage/test/cards/abilities/keywords/EvokeTest.java:44]: After going through the tests, it seems I was mistaken, All other examples of that pattern being used with trigger stacking actually were for ordering triggers with the same text, so I've only changed my own test here.

File: Mage/src/main/java/mage/abilities/keyword/EvokeAbility.java [hunk 3]
```diff
@@ -25,7 +25,7 @@ public EvokeAbility(String manaString) {
     public EvokeAbility(Cost cost) {
         super(EVOKE_KEYWORD, REMINDER_TEXT, cost);
         Ability ability = new ConditionalInterveningIfTriggeredAbility(
-                new EntersBattlefieldTriggeredAbility(new SacrificeSourceEffect()),
+                new EntersBattlefieldTriggeredAbility(new SacrificeSourceEffect(true)),
                 EvokedCondition.instance, "Sacrifice {this} when it enters the battlefield and was evoked.");
```
Comment (xenohedron) [inline Mage/src/main/java/mage/abilities/keyword/EvokeAbility.java:29]: update text to "When this permanent enters the battlefield, if its evoke cost was paid, its controller sacrifices it." per rules reference 702.74a

**Review by xenohedron — APPROVED** [review]
