### PR TITLE
fix Diluvian Primordial NPE on MDFC

### LINKED ISSUE #12176: IllegalStateException: MDFC in wrong zone
this error popped up when resolving a deluvian primordial that was targeting akroma's vengeance and valuakut awakening. vengeance resolved properly but when resolving the awaking, i selected cards to put on bottom and then this popped up.

Game error occurred: 

java.lang.IllegalStateException: Wrong code usage: MDF card uses wrong zones - Valakut Awakening [e9c] (ModalDoubleFacedCard -> ValakutAwakening)
* main zone: exile zone
* left side: need exile zone, actual GRAVEYARD
* right side: need exile zone, actual GRAVEYARD
Server version: 1.4.52-V7-beta9 (build: 2024-04-16 23:12)
Stack trace:
mage.cards.ModalDoubleFacedCard.checkGoodZones(ModalDoubleFacedCard.java:187)
mage.cards.ModalDoubleFacedCard.setSideZones(ModalDoubleFacedCard.java:113)
mage.cards.ModalDoubleFacedCard.moveToZone(ModalDoubleFacedCard.java:119)
mage.cards.ModalDoubleFacedCardHalfImpl.moveToZone(ModalDoubleFacedCardHalfImpl.java:54)
mage.cards.CardImpl.moveToZone(CardImpl.java:403)
mage.players.PlayerImpl.moveCardToGraveyardWithInfo(PlayerImpl.java:4955)
mage.players.PlayerImpl.moveCardsToGraveyardWithInfo(PlayerImpl.java:4939)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4715)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4690)
mage.players.PlayerImpl.moveCards(PlayerImpl.java:4681)
mage.game.stack.Spell.resolve(Spell.java:319)
mage.game.GameImpl.resolve(GameImpl.java:1766)
mage.game.GameImpl.playPriority(GameImpl.java:1689)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1131)
mage.game.GameImpl.play(GameImpl.java:1038)
mage.game.GameImpl.start(GameImpl.java:1014)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

### PR DESCRIPTION
**Pull request by Susucre**
There was actually 2 bugs:
- `MayCastTargetCardEffect` was not properly selecting the proper face of the card to cast for MDFC/Split/Adventure. `CardUtil::castSingle` had all the logic for that, just was missing the "without paying its mana cost" part.
- There was a bug on MDFC left/right faces zone tracking, that was not properly handling potential replacement effect on `ZoneChangeEvent` movements of the card. The left/right sides were wrongly set to the original destination.

Fix #12176

### CODE REVIEW

**Comment by xenohedron** [comment]
Does this address #10478, or is that separate?

**Comment by Susucre** [comment]
Uhm not sure, you did manual zcc tests right, not unit tested ones?
Will try to tweak the tests to have the current zcc values for permanent/card written explicitedly in the tests.

File: Mage/src/main/java/mage/cards/ModalDoubleFacedCard.java [hunk 1]
```diff
@@ -116,7 +116,7 @@ private void setSideZones(Zone mainZone, Game game) {
     @Override
     public boolean moveToZone(Zone toZone, Ability source, Game game, boolean flag, List<UUID> appliedEffects) {
         if (super.moveToZone(toZone, source, game, flag, appliedEffects)) {
-            setSideZones(toZone, game);
+            setSideZones(game.getState().getZone(getId()), game);
```
Comment (JayDi85) [inline Mage/src/main/java/mage/cards/ModalDoubleFacedCard.java:119]: it’s shared logic for all double faced cards. Must fix same way all other (both methods):

1.
IMG_0256

2.
IMG_0255

**Comment by Susucre** [comment]
@xenohedron you can look at the updated tests, all zcc is as expected for non-MDFC, and MDFC strangely have separate main/left/right that is not in sync (I can understand on the battlefield/stack, but in any other zones, I would expect those to be the same).

**Comment by JayDi85** [comment]
MDFC contains independent cards/parts. It's ok to have diff zcc.

**Comment by Susucre** [comment]
> MDFC contains independent cards/parts. It's ok to have diff zcc.
Really? Effects that look for the card with permanent ZCC + 1 in the next zone, would fail to find if the main card ZCC is not following the permanent ZCC?

I think that's why there are so many ZCC hacks all around, and sometimes it fails on MDFC.
Having them sync outside of battlefield seems way better.

**Comment by JayDi85** [comment]
Main card and half cards are different objects. As example: only one part go to stack and battlefield (another part go to outside) You can't take zcc from one object and apply it to another. Must use combo of "id + zcc" only. And that's why you can't use target from permanent/half -> main -- it's different. BTW same true for permanent -> card: after permanent move you must find real card for it (related to popular blink and commander replacement bugs).

**Comment by JayDi85** [comment]
You can make zcc sync broken test (real use cases with cards) in separate PR or commit with new issue to see how bad things are right now. Maybe it require some type of zcc sync or lki.

**Comment by Susucre** [comment]
I won't argue any more, and the PR's scope is actually solved here.

I still think that half the MDFC zcc handling is hacks because it is wrongly handled in the general movement methods.

**Comment by JayDi85** [comment]
> MDFC zcc handling is hacks because

If you talking about getMainCard usage then it's not a hack -- it a standard code style to work with objects after move between zones. And it's important.
